# Generated by Django 4.2 on 2026-04-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abia_arise_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nin', models.CharField(db_index=True, max_length=11, unique=True)),
                ('voters_card_no', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga_of_origin', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(default='Nigeria', max_length=100)),
                ('lga_of_residence', models.CharField(max_length=100)),
                ('state_of_residence', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(default='Nigeria', max_length=100)),
                ('electoral_ward', models.CharField(max_length=100)),
                ('polling_unit', models.CharField(max_length=100)),
                ('membership_purpose', models.TextField()),
                ('password_hash', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bvn', models.CharField(blank=True, max_length=11, null=True)),
                ('pin', models.CharField(default='0000', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_license_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lga', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_members', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='group_logos/')),
                ('chairman_name', models.CharField(max_length=200)),
                ('chairman_phone', models.CharField(max_length=20, unique=True)),
                ('chairman_email', models.EmailField(max_length=254)),
                ('chairman_residential_address', models.TextField()),
                ('chairman_passport', models.ImageField(upload_to='passports/chairman/')),
                ('chairman_password_hash', models.CharField(max_length=255)),
                ('secretary_name', models.CharField(max_length=200)),
                ('secretary_phone', models.CharField(max_length=20, unique=True)),
                ('secretary_email', models.EmailField(max_length=254)),
                ('secretary_residential_address', models.TextField()),
                ('secretary_passport', models.ImageField(upload_to='passports/secretary/')),
                ('secretary_password_hash', models.CharField(max_length=255)),
                ('members_database', models.FileField(blank=True, null=True, upload_to='member_databases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairman', 'Chairman'), ('secretary', 'Secretary'), ('member', 'Member')], default='member', max_length=20)),
                ('is_group_member', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.progroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_groups', to='accounts.individualmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('group', 'member')},
            },
        ),
    ]
