# Generated by Django 4.2 on 2026-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmember',
            name='account_status',
            field=models.CharField(choices=[('pending_activation', 'Pending Activation'), ('active', 'Active')], default='pending_activation', help_text='PENDING_ACTIVATION if via Excel only, ACTIVE if individually registered', max_length=20),
        ),
        migrations.AddField(
            model_name='individualmember',
            name='is_group_member',
            field=models.BooleanField(default=False, help_text='True if added via Pro-Group Excel upload'),
        ),
        migrations.AddField(
            model_name='individualmember',
            name='is_individual',
            field=models.BooleanField(default=True, help_text='True if self-registered as individual member'),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='country_of_origin',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='country_of_residence',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='electoral_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='lga_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='lga_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='membership_purpose',
            field=models.TextField(blank=True, help_text='Purpose for joining', null=True),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='polling_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='state_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individualmember',
            name='voters_card_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
