# Generated by Django 4.2 on 2026-04-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_individualmember_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progroup',
            name='pending_reset_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='progroup',
            name='pending_reset_pin_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progroup',
            name='pending_reset_pin_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='progroup',
            name='reset_pin',
            field=models.CharField(blank=True, help_text='PIN for reset/admin mode', max_length=6, null=True),
        ),
    ]
