# Generated by Django 4.2 on 2026-04-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_progroup_pending_reset_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progroup',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='group_excel_files/'),
        ),
    ]
