# Generated by Django 4.2 on 2026-04-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_progroup_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmember',
            name='id_card_file',
            field=models.FileField(blank=True, help_text='Path to generated ID card', null=True, upload_to='generated/id_cards/'),
        ),
        migrations.AddField(
            model_name='progroup',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Path to generated certificate', null=True, upload_to='generated/certificates/'),
        ),
    ]
