# Generated by Django 4.2 on 2026-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_groupmembership_membershipgroup_membershipuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progroup',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='progroup',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
